### PR TITLE
Jordan simons page

### PR DESCRIPTION
**Pull request by jordansimons20**
Created my personal page utilizing bootstrap. 

Large amount of files added due to bootstrap. Particularly, my HTML/CSS are in: 
startbootstrap-resume-gh-pages/jordan.html
startbootstrap-resume-gh-pages/css/jordan.css

### CODE REVIEW

**Comment by candre717** [comment]
LGTM

**Comment by chdastolfo** [comment]
👍 Overall this looks great. The only thing I would say is that you could clean up the included files a bit - you probably don't need the minified and regular versions of the same CSS file, for example. Usually unless I'm planning to make changes to the CSS framework files (which I almost never do), I'll delete the non-minified versions of the files and just include the minified ones. For the sake of this exercise you don't have to actually do that, just something to keep in mind! Nice job.

**Comment by jordansimons20** [comment]
I'll keep that in mind for the future, thanks!

**Comment by chdastolfo** [comment]
You're good to merge! I'll let you do the honors.

**Comment by jordansimons20** [comment]
🎉 🎉 🎉

**Pull request merged**
